quarkus:
  kafka:
    devservices:
      enabled: true

  kafka-streams:
    application-id: kstreams-dsl-naming
    topics:
      - "topic-a"
    bootstrap-servers: "localhost:9092"

    # To prevent malformed messages from killing the whole topology
    default:
      deserialization:
        exception:
          handler: "org.apache.kafka.streams.errors.LogAndContinueExceptionHandler"


# needed by Dev UI
kafka:
  bootstrap:
    servers: localhost:9092

# settings as per https://quarkus.io/guides/kafka-streams
#group.min.session.timeout.ms=250
#kafka-streams.consumer.session.timeout.ms=250
#kafka-streams.consumer.heartbeat.interval.ms=200