quarkus:
  kafka:
    devservices:
      enabled: true

custom:
  kafka:
    bootstrap-servers: "localhost:9092"
    application-id: kstreams-dsl-naming
    default-key-serde: "org.acme.qkt.StringSerde"
    default-value-serde: "org.acme.qkt.StringSerde"
    # To prevent malformed messages from killing the whole topology
    deserialization-exception-handler: "org.apache.kafka.streams.errors.LogAndContinueExceptionHandler"
    commit-interval-ms: 0
    save-topology-to-file: true

  kafka-streams:
    application-id: kstreams-dsl-naming
    topics:
      - "customer-events-v1"
      - "order-events-v1"
#    bootstrap-servers: "localhost:9092"

    # To prevent malformed messages from killing the whole topology
#    default:
#      deserialization:
#        exception:
#          handler: "org.apache.kafka.streams.errors.LogAndContinueExceptionHandler"
#      key:
#        serde: "org.acme.qkt.StringSerde"
#      value:
#        serde: "org.acme.qkt.StringSerde"


# needed by Dev UI
kafka:
  bootstrap:
    servers: localhost:9092

# settings as per https://quarkus.io/guides/kafka-streams
#group.min.session.timeout.ms=250
#kafka-streams.consumer.session.timeout.ms=250
#kafka-streams.consumer.heartbeat.interval.ms=200


